=== neatblackcrow/Software-construction/resources/configuration.dtd
<!ELEMENT config (setting)>
<!ELEMENT setting (theme, water_shade_color, water_color, thread_manager, thread_manual_threshold, windows_state)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT water_shade_color (#PCDATA)>
<!ELEMENT water_color (#PCDATA)>
<!ELEMENT thread_manager (#PCDATA)>
<!ELEMENT thread_manual_threshold (#PCDATA)>
<!ELEMENT windows_state (#PCDATA)>

=== neatblackcrow/Software-construction/resources/configuration.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- Please DO NOT EDIT this file directly --><!DOCTYPE config SYSTEM "configuration.dtd">
<config>
    <setting>
        <theme>SeaGlass</theme>
        <water_shade_color>0,0,0</water_shade_color>
        <water_color>0,0,0</water_color>
        <thread_manager>automatic</thread_manager>
        <thread_manual_threshold>0</thread_manual_threshold>
        <windows_state>0</windows_state>
    </setting>
</config>
